[package]
name = "blaze-editor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Blaze Engine editor binary"

[[bin]]
name = "blaze-editor"
path = "src/main.rs"

[dependencies]
blaze-core.workspace = true
blaze-app.workspace = true
blaze-ecs.workspace = true
blaze-input.workspace = true
blaze-math.workspace = true
blaze-render.workspace = true
blaze-physics.workspace = true
blaze-ui.workspace = true
blaze-script.workspace = true
log.workspace = true
env_logger.workspace = true
