[package]
name = "blaze-script"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Scripting plugin for Blaze Engine (rhai)"

[dependencies]
blaze-core.workspace = true
rhai.workspace = true
parking_lot.workspace = true
log.workspace = true
